<a href="https://colab.research.google.com/github/lovishdany/AI-ML__NCU/blob/main/Practical%20-%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "X":[78,80,81,82,84,80],
    "Y":[126,128,127,130,130,132]
})

X_mean = df["X"].mean()
Y_mean = df["Y"].mean()

standard_df = df.copy()
standard_df["X"] = standard_df["X"] - X_mean
standard_df["Y"] = standard_df["Y"] - Y_mean
standard_df

X         Y
0 -2.833333 -2.833333
1 -0.833333 -0.833333
2  0.166667 -1.833333
3  1.166667  1.166667
4  3.166667  1.166667
5 -0.833333  3.166667

In [ ]:
cov = standard_df.cov()
cov_arr = cov.to_numpy()
cov_arr

array([[4.16666667, 2.16666667],
       [2.16666667, 4.96666667]])

In [ ]:
eig_value, eig_vector = np.linalg.eig(cov_arr)
eig_value, eig_vector

(array([2.36338628, 6.76994705]),
 array([[-0.76861807, -0.63970795],
        [ 0.63970795, -0.76861807]]))